### PR TITLE
Create install_script.py

### PR DESCRIPTION
**Pull request by Bluscream**
Add easy install script to install the plugin into selected instances. (Use squash merge)

<details>
<summary>Example Log</summary>

```
2024-02-16 15:27:19,646 - DEBUG - Logging started at 2024-02-16 15:27:19.645767
2024-02-16 15:27:19,647 - DEBUG - WARNING: This log might contain sensitive information, like license keys, instance names and paths.
2024-02-16 15:27:19,647 - DEBUG - Do not share this log unaltered!
2024-02-16 15:27:19,648 - DEBUG - Script location: C:\Users\Administrator\Desktop\amp discord bot install.py
2024-02-16 15:27:24,299 - INFO - Found instances: ['ADS01', 'IW4xSNDPietSmiet01', 'IW4xTDMPietSmiet01', 'VDEAMPDiscordBot01', 'VDEAPIRunner01', 'VDEClanServer01', 'VDECommunityServer01']
2024-02-16 15:27:29,427 - INFO - Skipping instance VDEAMPDiscordBot01
2024-02-16 15:27:31,851 - INFO - Selected instances: ['ADS01', 'IW4xSNDPietSmiet01', 'IW4xTDMPietSmiet01', 'VDEAPIRunner01', 'VDEClanServer01', 'VDECommunityServer01']
2024-02-16 15:27:31,853 - INFO - Stopping instance ADS01
2024-02-16 15:27:31,854 - DEBUG - Executing command: ['ampinstmgr', 'stop', 'ADS01']
2024-02-16 15:27:32,928 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Notice] ADS01 is already stopped.

2024-02-16 15:27:32,929 - DEBUG - 
2024-02-16 15:27:32,929 - INFO - Stopping instance IW4xSNDPietSmiet01
2024-02-16 15:27:32,930 - DEBUG - Executing command: ['ampinstmgr', 'stop', 'IW4xSNDPietSmiet01']
2024-02-16 15:27:33,740 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Notice] IW4xSNDPietSmiet01 is already stopped.

2024-02-16 15:27:33,740 - DEBUG - 
2024-02-16 15:27:33,740 - INFO - Stopping instance IW4xTDMPietSmiet01
2024-02-16 15:27:33,740 - DEBUG - Executing command: ['ampinstmgr', 'stop', 'IW4xTDMPietSmiet01']
2024-02-16 15:27:34,563 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Notice] IW4xTDMPietSmiet01 is already stopped.

2024-02-16 15:27:34,563 - DEBUG - 
2024-02-16 15:27:34,563 - INFO - Stopping instance VDEAPIRunner01
2024-02-16 15:27:34,568 - DEBUG - Executing command: ['ampinstmgr', 'stop', 'VDEAPIRunner01']
2024-02-16 15:27:35,435 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Notice] VDEAPIRunner01 is already stopped.

2024-02-16 15:27:35,435 - DEBUG - 
2024-02-16 15:27:35,436 - INFO - Stopping instance VDEClanServer01
2024-02-16 15:27:35,436 - DEBUG - Executing command: ['ampinstmgr', 'stop', 'VDEClanServer01']
2024-02-16 15:27:36,178 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Notice] VDEClanServer01 is already stopped.

2024-02-16 15:27:36,179 - DEBUG - 
2024-02-16 15:27:36,179 - INFO - Stopping instance VDECommunityServer01
2024-02-16 15:27:36,179 - DEBUG - Executing command: ['ampinstmgr', 'stop', 'VDECommunityServer01']
2024-02-16 15:27:37,056 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Notice] VDECommunityServer01 is already stopped.

2024-02-16 15:27:37,056 - DEBUG - 
2024-02-16 15:27:37,056 - INFO - Reactivating instance ADS01
2024-02-16 15:27:37,056 - DEBUG - Executing command: ['ampinstmgr', 'reactivate', 'ADS01', '<REDACTED>']
2024-02-16 15:27:43,512 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info] Checking licence key...
[Info] Licence Type:  AMP Developer
[Info] Current Usage: 6
[Info] Reactivating instance ADS01...
[Info] Done.

2024-02-16 15:27:43,513 - DEBUG - 
2024-02-16 15:27:43,513 - INFO - Reactivating instance IW4xSNDPietSmiet01
2024-02-16 15:27:43,515 - DEBUG - Executing command: ['ampinstmgr', 'reactivate', 'IW4xSNDPietSmiet01', '<REDACTED>']
2024-02-16 15:27:49,334 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info] Checking licence key...
[Info] Licence Type:  AMP Developer
[Info] Current Usage: 6
[Info] Reactivating instance IW4xSNDPietSmiet01...
[Info] Done.

2024-02-16 15:27:49,334 - DEBUG - 
2024-02-16 15:27:49,334 - INFO - Reactivating instance IW4xTDMPietSmiet01
2024-02-16 15:27:49,336 - DEBUG - Executing command: ['ampinstmgr', 'reactivate', 'IW4xTDMPietSmiet01', '<REDACTED>']
2024-02-16 15:27:55,316 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info] Checking licence key...
[Info] Licence Type:  AMP Developer
[Info] Current Usage: 6
[Info] Reactivating instance IW4xTDMPietSmiet01...
[Info] Done.

2024-02-16 15:27:55,317 - DEBUG - 
2024-02-16 15:27:55,318 - INFO - Reactivating instance VDEAPIRunner01
2024-02-16 15:27:55,320 - DEBUG - Executing command: ['ampinstmgr', 'reactivate', 'VDEAPIRunner01', '<REDACTED>']
2024-02-16 15:28:02,160 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info] Checking licence key...
[Info] Licence Type:  AMP Developer
[Info] Current Usage: 6
[Info] Reactivating instance VDEAPIRunner01...
[Info] Done.

2024-02-16 15:28:02,161 - DEBUG - 
2024-02-16 15:28:02,161 - INFO - Reactivating instance VDEClanServer01
2024-02-16 15:28:02,164 - DEBUG - Executing command: ['ampinstmgr', 'reactivate', 'VDEClanServer01', '<REDACTED>']
2024-02-16 15:28:09,563 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info] Checking licence key...
[Info] Licence Type:  AMP Developer
[Info] Current Usage: 6
[Info] Reactivating instance VDEClanServer01...
[Info] Done.

2024-02-16 15:28:09,563 - DEBUG - 
2024-02-16 15:28:09,563 - INFO - Reactivating instance VDECommunityServer01
2024-02-16 15:28:09,564 - DEBUG - Executing command: ['ampinstmgr', 'reactivate', 'VDECommunityServer01', '<REDACTED>']
2024-02-16 15:28:16,314 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info] Checking licence key...
[Info] Licence Type:  AMP Developer
[Info] Current Usage: 6
[Info] Reactivating instance VDECommunityServer01...
[Info] Done.

2024-02-16 15:28:16,314 - DEBUG - 
2024-02-16 15:28:16,314 - DEBUG - Executing command: ['taskkill', '/f', '/im', 'AMP.exe']
2024-02-16 15:28:16,495 - DEBUG - 
2024-02-16 15:28:16,497 - DEBUG - ERROR: The process "AMP.exe" not found.

2024-02-16 15:28:16,497 - INFO - Processing instance ADS01
2024-02-16 15:28:16,497 - INFO - Copying C:\Users\Administrator\Desktop\DiscordBotPlugin.dll to C:\AMPDatastore\Instances\ADS01\Plugins\DiscordBotPlugin
2024-02-16 15:28:16,497 - INFO - C:\AMPDatastore\Instances\ADS01\Plugins\DiscordBotPlugin\DiscordBotPlugin.dll already exists, overwriting
2024-02-16 15:28:16,515 - INFO - Updating AMPConfig.conf at C:\AMPDatastore\Instances\ADS01\AMPConfig.conf
2024-02-16 15:28:16,516 - INFO - DiscordBotPlugin already in AMP.LoadPlugins
2024-02-16 15:28:16,519 - INFO - Processing instance IW4xSNDPietSmiet01
2024-02-16 15:28:16,520 - INFO - Copying C:\Users\Administrator\Desktop\DiscordBotPlugin.dll to C:\AMPDatastore\Instances\IW4xSNDPietSmiet01\Plugins\DiscordBotPlugin
2024-02-16 15:28:16,521 - INFO - C:\AMPDatastore\Instances\IW4xSNDPietSmiet01\Plugins\DiscordBotPlugin\DiscordBotPlugin.dll already exists, overwriting
2024-02-16 15:28:16,527 - INFO - Updating AMPConfig.conf at C:\AMPDatastore\Instances\IW4xSNDPietSmiet01\AMPConfig.conf
2024-02-16 15:28:16,545 - INFO - DiscordBotPlugin already in AMP.LoadPlugins
2024-02-16 15:28:16,545 - INFO - Processing instance IW4xTDMPietSmiet01
2024-02-16 15:28:16,549 - INFO - Copying C:\Users\Administrator\Desktop\DiscordBotPlugin.dll to C:\AMPDatastore\Instances\IW4xTDMPietSmiet01\Plugins\DiscordBotPlugin
2024-02-16 15:28:16,551 - INFO - C:\AMPDatastore\Instances\IW4xTDMPietSmiet01\Plugins\DiscordBotPlugin\DiscordBotPlugin.dll already exists, overwriting
2024-02-16 15:28:16,564 - INFO - Updating AMPConfig.conf at C:\AMPDatastore\Instances\IW4xTDMPietSmiet01\AMPConfig.conf
2024-02-16 15:28:16,575 - INFO - DiscordBotPlugin already in AMP.LoadPlugins
2024-02-16 15:28:16,581 - INFO - Processing instance VDEAPIRunner01
2024-02-16 15:28:16,586 - INFO - Copying C:\Users\Administrator\Desktop\DiscordBotPlugin.dll to C:\AMPDatastore\Instances\VDEAPIRunner01\Plugins\DiscordBotPlugin
2024-02-16 15:28:16,598 - INFO - C:\AMPDatastore\Instances\VDEAPIRunner01\Plugins\DiscordBotPlugin\DiscordBotPlugin.dll already exists, overwriting
2024-02-16 15:28:16,614 - INFO - Updating AMPConfig.conf at C:\AMPDatastore\Instances\VDEAPIRunner01\AMPConfig.conf
2024-02-16 15:28:16,616 - INFO - DiscordBotPlugin already in AMP.LoadPlugins
2024-02-16 15:28:16,617 - INFO - Processing instance VDEClanServer01
2024-02-16 15:28:16,618 - INFO - Copying C:\Users\Administrator\Desktop\DiscordBotPlugin.dll to C:\AMPDatastore\Instances\VDEClanServer01\Plugins\DiscordBotPlugin
2024-02-16 15:28:16,620 - INFO - C:\AMPDatastore\Instances\VDEClanServer01\Plugins\DiscordBotPlugin\DiscordBotPlugin.dll already exists, overwriting
2024-02-16 15:28:16,645 - INFO - Updating AMPConfig.conf at C:\AMPDatastore\Instances\VDEClanServer01\AMPConfig.conf
2024-02-16 15:28:16,653 - INFO - DiscordBotPlugin already in AMP.LoadPlugins
2024-02-16 15:28:16,659 - INFO - Processing instance VDECommunityServer01
2024-02-16 15:28:16,662 - INFO - Copying C:\Users\Administrator\Desktop\DiscordBotPlugin.dll to C:\AMPDatastore\Instances\VDECommunityServer01\Plugins\DiscordBotPlugin
2024-02-16 15:28:16,664 - INFO - C:\AMPDatastore\Instances\VDECommunityServer01\Plugins\DiscordBotPlugin\DiscordBotPlugin.dll already exists, overwriting
2024-02-16 15:28:16,687 - INFO - Updating AMPConfig.conf at C:\AMPDatastore\Instances\VDECommunityServer01\AMPConfig.conf
2024-02-16 15:28:16,692 - INFO - DiscordBotPlugin already in AMP.LoadPlugins
2024-02-16 15:28:43,345 - INFO - C:\AMPDatastore\Instances\IW4xSNDPietSmiet01\DiscordBotPlugin.kvp already exists, skipping
2024-02-16 15:28:43,346 - INFO - C:\AMPDatastore\Instances\IW4xTDMPietSmiet01\DiscordBotPlugin.kvp already exists, skipping
2024-02-16 15:28:43,347 - INFO - C:\AMPDatastore\Instances\VDEAPIRunner01\DiscordBotPlugin.kvp already exists, skipping
2024-02-16 15:28:43,348 - INFO - C:\AMPDatastore\Instances\VDEClanServer01\DiscordBotPlugin.kvp already exists, skipping
2024-02-16 15:28:43,350 - INFO - C:\AMPDatastore\Instances\VDECommunityServer01\DiscordBotPlugin.kvp already exists, skipping
2024-02-16 15:28:43,350 - INFO - Starting instance ADS01
2024-02-16 15:28:43,350 - DEBUG - Executing command: ['ampinstmgr', 'start', 'ADS01']
2024-02-16 15:28:47,959 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info] Starting Instance: 'ADS01'
[Info] You can browse to this instance at http://10.253.0.1:8080/
[Info] Instance started in new session. Run 'ampinstmgr View ADS01' to view this instances live output.

2024-02-16 15:28:47,959 - DEBUG - 
2024-02-16 15:28:47,959 - INFO - Starting instance IW4xSNDPietSmiet01
2024-02-16 15:28:47,959 - DEBUG - Executing command: ['ampinstmgr', 'start', 'IW4xSNDPietSmiet01']
2024-02-16 15:28:48,819 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info] Starting Instance: 'IW4xSNDPietSmiet01'
[Error] This instance can only be started by ADS (AMP's main web interface) - it cannot be started via the command line.
[Info] This instance failed to start. Run 'ampinstmgr LastLog IW4xSNDPietSmiet01' to view it's most recent log.

2024-02-16 15:28:48,820 - DEBUG - 
2024-02-16 15:28:48,820 - INFO - Starting instance IW4xTDMPietSmiet01
2024-02-16 15:28:48,823 - DEBUG - Executing command: ['ampinstmgr', 'start', 'IW4xTDMPietSmiet01']
2024-02-16 15:28:49,887 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info] Starting Instance: 'IW4xTDMPietSmiet01'
[Error] This instance can only be started by ADS (AMP's main web interface) - it cannot be started via the command line.
[Info] This instance failed to start. Run 'ampinstmgr LastLog IW4xTDMPietSmiet01' to view it's most recent log.

2024-02-16 15:28:49,888 - DEBUG - 
2024-02-16 15:28:49,888 - INFO - Starting instance VDEAPIRunner01
2024-02-16 15:28:49,897 - DEBUG - Executing command: ['ampinstmgr', 'start', 'VDEAPIRunner01']
2024-02-16 15:28:50,681 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info] Starting Instance: 'VDEAPIRunner01'
[Error] This instance can only be started by ADS (AMP's main web interface) - it cannot be started via the command line.
[Info] This instance failed to start. Run 'ampinstmgr LastLog VDEAPIRunner01' to view it's most recent log.

2024-02-16 15:28:50,681 - DEBUG - 
2024-02-16 15:28:50,681 - INFO - Starting instance VDEClanServer01
2024-02-16 15:28:50,684 - DEBUG - Executing command: ['ampinstmgr', 'start', 'VDEClanServer01']
2024-02-16 15:28:51,466 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info] Starting Instance: 'VDEClanServer01'
[Error] This instance can only be started by ADS (AMP's main web interface) - it cannot be started via the command line.
[Info] This instance failed to start. Run 'ampinstmgr LastLog VDEClanServer01' to view it's most recent log.

2024-02-16 15:28:51,468 - DEBUG - 
2024-02-16 15:28:51,468 - INFO - Starting instance VDECommunityServer01
2024-02-16 15:28:51,469 - DEBUG - Executing command: ['ampinstmgr', 'start', 'VDECommunityServer01']
2024-02-16 15:28:52,408 - DEBUG - [Info] AMP Instance Manager v2.4.6.10 built 06/12/2023 17:18
[Info] Stream: Mainline / Release - built by CUBECODERS/buildbot on CCL-DEV
[Info] Starting Instance: 'VDECommunityServer01'
[Error] This instance can only be started by ADS (AMP's main web interface) - it cannot be started via the command line.
[Info] This instance failed to start. Run 'ampinstmgr LastLog VDECommunityServer01' to view it's most recent log.

2024-02-16 15:28:52,409 - DEBUG - 

```

</details>

### CODE REVIEW

**Comment by winglessraven** [comment]
This is great, thanks!

How's your Linux knowledge? It would be great to have this work for Windows and Linux. My Python knowledge is non-existent unfortunatley.

The taskkill step will only work on Windows, Linux gives these errors...

```Traceback (most recent call last):
  File "/home/amp/install_script.py", line 132, in <module>
    execute_os_command(['taskkill', '/f', '/im', amp_process_name])
  File "/home/amp/install_script.py", line 48, in execute_os_command
    process = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'taskkill'
```

**Comment by winglessraven** [comment]
ChatGPT suggesting os module...

```python
import os

def kill_amp_process():
    if os.name == 'nt':  # Windows
        execute_os_command(['taskkill', '/f', '/im', amp_process_name])
    elif os.name == 'posix':  # Linux
        execute_os_command(['pkill', '-f', amp_process_name])
```

**Comment by Bluscream** [comment]
> This is great, thanks!
> 
> How's your Linux knowledge? It would be great to have this work for Windows and Linux. My Python knowledge is non-existent unfortunatley.
> 
> The taskkill step will only work on Windows, Linux gives these errors...
> 
> ```
>   File "/home/amp/install_script.py", line 132, in <module>
>     execute_os_command(['taskkill', '/f', '/im', amp_process_name])
>   File "/home/amp/install_script.py", line 48, in execute_os_command
>     process = subprocess.run(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE, text=True)
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/subprocess.py", line 548, in run
>     with Popen(*popenargs, **kwargs) as process:
>          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.11/subprocess.py", line 1024, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/usr/lib/python3.11/subprocess.py", line 1901, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: 'taskkill'
> ```



> ChatGPT suggesting os module...
> 
> ```python
> import os
> 
> def kill_amp_process():
>     if os.name == 'nt':  # Windows
>         execute_os_command(['taskkill', '/f', '/im', amp_process_name])
>     elif os.name == 'posix':  # Linux
>         execute_os_command(['pkill', '-f', amp_process_name])
> ```

Exactly that should work, i never tried installing this bot on linux since the other bot that you can install through AMP directly worked there. But sure i think i enabled "Edits by maintainers" for this PR, otherwise i can put it in with another commit if you want

**Review by winglessraven — APPROVED** [review]
Amazing work, thank you :)

**Comment by Bluscream** [comment]
You rock 💪🏻

**Pull request merged**
